services: 
  frontend:
    container_name: frontend
    image: plutou/webimmunization-frontend:devel
    ports:
      - "3001:3000"
    networks:
      - express_nw
    restart: always
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 frontend

networks:
  express_nw:
    driver: bridge